// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.920
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index(body templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>All Posts - Admin Panel</title><script src=\"https://cdn.tailwindcss.com\"></script><script src=\"https://unpkg.com/htmx.org@1.9.12\"></script><style>\n        /* Simple style for dark theme */\n        body { background-color: #111827; color: #d1d5db; }\n        .table-header { background-color: #374151; }\n        .table-row { background-color: #1f2937; }\n        .sidebar { background-color: #1f2937; }\n        .main-content { background-color: #111827; }\n        .tab-active { border-color: #3b82f6; background-color: #1f2937; }\n        .tab-inactive { border-color: #4b5563; }\n    </style></head><body class=\"font-sans\"><div class=\"flex h-screen\"><aside class=\"w-48 sidebar p-4\"><h1 class=\"text-xl font-bold text-white mb-6\">Admin Panel</h1><nav class=\"flex flex-col space-y-2\"><a href=\"#\" class=\"bg-gray-700 text-white rounded-md p-2\">All Posts</a> <a href=\"add-new.html\" class=\"hover:bg-gray-700 rounded-md p-2\">Add New</a> <a href=\"preview.html\" class=\"hover:bg-gray-700 rounded-md p-2\">Preview Blog</a></nav></aside>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = body.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
